### ISSUE TITLE
Build fails due to tsconfig.app.json file missing from repository

### ISSUE THREAD

**Issue by IainStevenson** [Everduin94/component-communication-patterns#1]
Not sure if this project was intended to be build-able or run-able but ...

There seems to be a number of files missing from the project to my eye, but in particular, the following angular.json file reference is missing, and the build fails.

`"tsConfig": "src/tsconfig.app.json",`

Rendering this error message after npm install and ng build...

> NOENT: no such file or directory, stat 'C:\Users\<me>\source\repos\component-communication-patterns\src\tsconfig.app.json'
Error: ENOENT: no such file or directory, stat 'C:\Users\<me>\source\repos\component-communication-patterns\src\tsconfig.app.json'
    at Object.statSync (fs.js:855:3)
    at AngularCompilerPlugin._setupOptions (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:85:16)
    at new AngularCompilerPlugin (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:53:14)
    at _createAotPlugin (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\typescript.js:41:12)
    at Object.getNonAotConfig (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\typescript.js:47:19)
    at BrowserBuilder.buildWebpackConfig (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular-devkit\build-angular\src\browser\index.js:82:37)
    at MergeMapSubscriber.rxjs_1.of.pipe.operators_1.concatMap [as project] (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular-devkit\build-angular\src\browser\index.js:30:38)
    at MergeMapSubscriber._tryNext (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:67:18)
    at SafeSubscriber.__tryOrUnsub (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:209:16)
    at SafeSubscriber.next (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:147:22)
    at Subscriber._next (C:\Users\<me>\source\repos\component-communication-patterns\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:90:26)

**Comment by richie50** [comment]
I added the config files. But i cannot submit a pull request @Everduin94

**Comment by Everduin94** [comment]
@IainStevenson Thank you for creating the issue. I created the project from Stackblitz and didn't realize it was missing the necessary config files for running without Stackblitz.

@richie50 Thank you for mentioning me and creating the config files. -- I have a solution mentioned below.

I've created a separate branch "forkable" that has the project in a standalone runnable state. If I add the config files to master it seems to break the project on Stackblitz. Please let me know if this is a valid solution for you all and I'll update the read me to note this.

**Comment by richie50** [comment]
@Everduin94 config files are created. Feel free to merge them. Thanks

**Comment by Everduin94** [comment]
Closing, please see forkable branch for the standalone version. In the future, I will keep the Stackblitz project separate from the Github repository when working with Angular projects.

**Comment by Everduin94** [comment]
@IainStevenson @richie50 

I fixed the master branch to work standalone and on Stackblitz. -- Stackblitz uses a selector for appComponent that was not present and I completely overlooked this after merging richie's pull request, -- Sorry I'm a doofus 😅
